fixed kill not responding
this was due to there not being a variable that it could reference called `'last_kill_id'`

discord.app_commands.errors.CommandInvokeError: Command 'killed' raised an exception: AttributeError: 'Boss' object has no attribute 'last_kill_id'
[2023-02-08 07:00:33] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'killed'